name: Bug Report
description: Report a reproducible problem in the site
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce quickly.
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: Briefly describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Browser / device
      placeholder: Chrome 123 / Windows 11 / Desktop
