name: Feature Request
description: Suggest an improvement to the product or repo workflow
labels: [enhancement]
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      placeholder: What pain point are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the solution and expected impact
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other options you evaluated
